### ISSUE TITLE
Tabulator rolls down page when I show a modal using @click-row event

### ISSUE THREAD

**Issue by clustersnake** [angeliski/vue-tabulator#56]
I created this [example](https://codesandbox.io/s/bootstrap-vue-4k89l?file=/src/components/HelloWorld.vue) using bootstrap-vue, I tested with quasar framework and the same thing happens. Could you please help me out here?

**Comment by angeliski** [comment]
Hey @clustersnake 
Thanks for your issue,
I will try to find the problem here

**Comment by angeliski** [comment]
@clustersnake 
The problem is about the [modal focus function](https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/modal/modal.js#L843).
I used workaround here: https://codesandbox.io/s/bootstrap-vue-m4knj

Just put a `:return-focus="'body'"` in the modal to evict call focus fuction

Could that help you?


Cheers

**Comment by clustersnake** [comment]
You are a real life saver my friend! that worked perfect. Thank you very much.
